# Generated by Django 5.2.8 on 2026-02-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
