# Generated by Django 5.2.8 on 2026-02-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_crud', '0003_alter_customuser_cedula_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
