# Generated by Django 6.1 on 2026-09-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_crud', '0004_alter_customuser_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
